### ISSUE TITLE
The bot is not playing music

### ISSUE THREAD

**Issue by mynameiskira** [lol123Xb/Anime-Radio-Club-Discord-Bot#3]
Despite joining the vocal lounge, the bot does not produce any sound

` message.channel.send(embed);
        message.member.voice.channel.join().then(connection => {
          require('http').get("http://radio.animenexus.mx:8000/animenexus", (res) => {
            connection.play(res).on('error', err => {
              client.logger.error(err);
              connection.play(res)
            })
          })
        })`

`client.logger.error(err);
                          ^

TypeError: Cannot read property 'error' of undefined`

**Comment by lol123Xb** [comment]
just remove that line
so its just
`connection.play(res)`
